const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const IMPAR = 'IMPAR';
const INCREMENTARASYNC = 'INCREMENTARASYNC';
const BUSCARNOMBRE = 'BUSCARNOMBRE';

module.exports = {
  INCREMENTO,
  DECREMENTO,
  IMPAR,
  INCREMENTARASYNC,
  BUSCARNOMBRE
}